### ISSUE TITLE
It does not work anymore

### ISSUE THREAD

**Issue by RedSquirrel87** [Razzeee/context.trakt.watched#1]
I get an error when I use the context menu option for this addon.
This is the kodi.log explanation of the error:

> 2020-12-25 21:49:46.564 T:3287282560   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                              - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                             Error Type: <type 'exceptions.KeyError'>
>                                             Error Contents: 'imdbnumber'
>                                             Traceback (most recent call last):
>                                               File "/storage/.kodi/addons/script.trakt/defaultscript.py", line 14, in <module>
>                                                 Main()
>                                               File "/storage/.kodi/addons/script.trakt/defaultscript.py", line 11, in Main
>                                                 script.run()
>                                               File "/storage/.kodi/addons/script.trakt/resources/lib/script.py", line 171, in run
>                                                 data['id'] = result['imdbnumber']
>                                             KeyError: 'imdbnumber'
>                                             -->End of Python script error report<--

**Comment by razzeee** [comment]
Which scraper are you using? NFO files? Do you set `imdbnumber`?

**Comment by RedSquirrel87** [comment]
I'm using tmdb for movies and thetvdb for TV series, no NFO files

**Comment by RedSquirrel87** [comment]
I forgot to mention that I'm using also the "Rating button" addon and it works like a charm. Only the "Watched button" addon gives the error

**Comment by razzeee** [comment]
Please post a complete log

**Comment by RedSquirrel87** [comment]
I'll do it asap, but the only "error" message is that one attached in the first post.
However it seems to be the same issue already reported in your other addon (I found this issue https://github.com/Razzeee/context.trakt.addtowatchlist/issues/1 ) because the error message is the same and even for me it happens only with TV series, it works with movies. 
I'm using the versions in the official Kodi repository, is it possible that they are still deprecated versions there?

**Comment by razzeee** [comment]
Probable, most testing is done on matrix these days. That's also something I would have seen with a complete log.
